name: sdf1
version: 1.3
author: Sdf1_team
main: com.sdf1.Main
api-version: 1.21
softdepend: [CY_beibao]
commands:
  sdf1:
    description: 主命令
    usage: /sdf1
    permission: cy.use
    permission-message: §c你没有权限使用此命令
  import:
    description: 导入口令
    permission: import.op
    permission-message: 无权限
permissions:
  sdf1.use:
    description: 使用 /sdf1 基础命令
    default: true
  sdf1.admin:
    description: 管理员权限（reload/update）
    default: op
