name: sdf1
version: 1.1
author: Sdf1_team
# 这里的路径必须指向你的 Main 类，注意大小写！
main: com.sdf1.Main
# 必须声明 API 版本，否则 1.21.4 会报错
api-version: 1.21
softdepend: [CY_beibao]
commands:
  sdf1:
    description: 主控激活口令指令
    usage: /sdf1